name: Website Truyện Chữ
theme: minima
baseurl: ""
url: "https://username.github.io"
collections:
  stories:
    output: true
    permalink: /:collection/:title

header: "Website Truyện Chữ Của Phạm Băng"
